networks:
  gitea:

volumes:
  gitea_data:

services:
  gitea:
    container_name: gitea
    # image: gitea/gitea:latest-rootless
    image: gitea/gitea:latest
    restart: always
    ports:
      # Default ports
      - "3000:3000"
      - "2222:2222"
      # [Optional] Custom ports, should match Nginx/gateway confs
      # Remember to comment out the above defaults
      # - "8081:3000"
    networks:
      - gitea
    volumes:
      - gitea_data:/data
      - ./config:/data/gitea/conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
