networks:
  gitea:

volumes:
  gitea_data:

services:
  gitea:
    container_name: gitea
    image: gitea/gitea:latest-rootless
    # image: gitea/gitea:latest
    restart: always
    env_file: .env
    ports:
      # Should match Nginx/gateway confs
      - ${PORT-3000}:3000
      - ${PORT_SSH-2222}:2222
    networks:
      - gitea
    volumes:
      - gitea_data:/data
      - ./config:/etc/gitea/conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
