version: "3.9"

networks:
  gitea:
    external: false

volumes:
  gitea_data:

services:
  gitea:
    image: gitea/gitea:latest-rootless
    restart: always
    ports:
      # Default ports
      - "3000:3000"
      - "2222:2222"
      # [Optional] Custom ports
      # - "8081:3000" # Should match Nginx conf
    networks:
      - gitea
    volumes:
      - gitea_data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
