version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea_data:

services:
  gitea:
    image: gitea/gitea
    restart: always
    ports:
      - "3000:3000"
      - "222:22"
    networks:
      - gitea
    volumes:
      - gitea_data:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
